## Importing Libraries

In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Importing Dataset

In [19]:
df = pd.read_csv('tennis.csv')
df

outlook  temp humidity  windy play
0      sunny   hot     high  False   no
1      sunny   hot     high   True   no
2   overcast   hot     high  False  yes
3      rainy  mild     high  False  yes
4      rainy  cool   normal  False  yes
5      rainy  cool   normal   True   no
6   overcast  cool   normal   True  yes
7      sunny  mild     high  False   no
8      sunny  cool   normal  False  yes
9      rainy  mild   normal  False  yes
10     sunny  mild   normal   True  yes
11  overcast  mild     high   True  yes
12  overcast   hot   normal  False  yes
13     rainy  mild     high   True   no

## Column Transformation

In [20]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

columns = list(df.columns)
play = columns.pop(4)

for column in columns:
    df[column] = le.fit_transform(df[column])

df

outlook  temp  humidity  windy play
0         2     1         0      0   no
1         2     1         0      1   no
2         0     1         0      0  yes
3         1     2         0      0  yes
4         1     0         1      0  yes
5         1     0         1      1   no
6         0     0         1      1  yes
7         2     2         0      0   no
8         2     0         1      0  yes
9         1     2         1      0  yes
10        2     2         1      1  yes
11        0     2         0      1  yes
12        0     1         1      0  yes
13        1     2         0      1   no

## Allocating column values to x&y variables

In [21]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]

## Feature Scaling

In [22]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X = scaler.fit_transform(x)
print(X)

[[ 1.16275535 -0.17149859 -1.         -0.8660254 ]
 [ 1.16275535 -0.17149859 -1.          1.15470054]
 [-1.34164079 -0.17149859 -1.         -0.8660254 ]
 [-0.08944272  1.02899151 -1.         -0.8660254 ]
 [-0.08944272 -1.37198868  1.         -0.8660254 ]
 [-0.08944272 -1.37198868  1.          1.15470054]
 [-1.34164079 -1.37198868  1.          1.15470054]
 [ 1.16275535  1.02899151 -1.         -0.8660254 ]
 [ 1.16275535 -1.37198868  1.         -0.8660254 ]
 [-0.08944272  1.02899151  1.         -0.8660254 ]
 [ 1.16275535  1.02899151  1.          1.15470054]
 [-1.34164079  1.02899151 -1.          1.15470054]
 [-1.34164079 -0.17149859  1.         -0.8660254 ]
 [-0.08944272  1.02899151 -1.          1.15470054]]


## Splitting the Dataset

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size = 0.2, random_state = 2)

## Training the Naive Baye's Model

In [24]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(x,y)

GaussianNB()

## Predicting the values

In [25]:
y_pred = gnb.predict(X_test)
print(y_pred)

['yes' 'yes' 'yes']
